# Sum of even fibonacci series
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def generate_fibonacci(limit):
    operand1 = 0
    operand2 = 1
    fibonacci_sum = 0
    while(True):
        operand3 = operand1 + operand2
        if operand3 > limit:
            break
        fibonacci_sum += operand3
        operand1 = operand2
        operand2 = operand3
    return fibonacci_sum

limit = int(input("Enter the number upto which the sum should be: "))
print("The sum of fibonacci numbers below {} is {}".format(limit,generate_fibonacci(limit)))
